title: Helen Walpole
logo: "/images/logo.png?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Designing creative, meaningful experiences 
  <br><br>
  (Respectfully irreverent)
  <br><br>
  <a href="https://www.linkedin.com/in/helenwalpole/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
